[package]
name = "guefi-worker"
version = "0.1.0"
edition = "2021"

license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipc-rpc = "1.2.6"
