[package]
name = "guefi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.0"
ipc-rpc = "1.2.6"
guefi-lib = { path = "../guefi-lib" }