[package]
name = "guefi-lib"
version = "0.1.0"
edition = "2021"

license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
efivar = "2.0.0"
schemars = "0.8.16"
serde = "1.0.197"
